# -*- coding: utf-8 -*-
"""shai .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1435yIM3Fn9tkfwZOC5IzOER4TRQl963v
"""

import pandas as pd
import numpy as np
df=pd.read_csv('/content/Salaries.csv')
df.head()

df.columns

#number of columns and row
df.shape

#type of each cloumns
df.dtypes

#checking for missing values
print("missing values are \n",df.isnull().sum())

df['TotalPay'].min()

df['TotalPay'].std()

df['TotalPay'].max()

df['TotalPay'].mean()

df['TotalPay'].median()

df['TotalPay'].mode()

#range calculation
range=df['TotalPay'].max()-df['TotalPay'].min()
print( 'range=',range)

#handle the missing value
newdf=df.fillna({'BasePay':df['BasePay'].mean(),'OvertimePay':df['OvertimePay'].mean(),'OtherPay':df['OtherPay'].mean(),'Benefits':0,'Year':df['Year'].mean(),'Notes':'Nothing','Status':'Nothing'})

newdf.isnull().sum()

import matplotlib.pyplot as plt
plt.hist(newdf['TotalPay'],bins=20,color='green',edgecolor='yellow')
plt.title('distribution of salaries')
plt.xlabel('Salaries(totalpay)')
plt.ylabel('Distibution')
plt.show()

depcount=newdf['JobTitle'].value_counts()
plt.bar(depcount.index,depcount.values,color='red')
plt.title('Proportion of Employee in Different Department')
plt.xlabel('Department')
plt.ylabel('number of employee')
plt.xticks(rotation=45,ha='right')
plt.show()

newdf.groupby('Year')['TotalPay'].describe()

#correlation calculation
newdf['TotalPay'].corr(newdf['Year'])

#scatter plot to visualize the relationship
plt.scatter(newdf['TotalPay'],newdf['Year'],alpha=0.5)#numerical column=year
plt.title('Scatter Plot: Salary(total pay) vs Years of Experience(numerical column)')
plt.xlabel('Years ')
plt.ylabel('Salary(totalpay)')
plt.show()

"""Summary:
The dataset is very large, so I used df.head() to display the first five rows,to determine the type of each column i used df.dtype and to check the number of column and row i used df.shape : the first number represnt a number of rows and the second number represnt a numberof columns, to check the missing values for each column i used isnull().sum.
To calculate the baics statistics : all the function that i used are there in Pandas , and  the range is the max value-min value.
For handeling missing value: i used more than one method , mean value method  in column that i  want represents all values ​​and does not represent a random unit value, so that the accuracy is fairly good, the second method : default value such as '0'  'nothing' for column that are not important or not effictive in dataset .
I called matplotlib.pyplot to visualization many relationship between different columns(i used a newdf because it doesnt include missing value ) , 'Distribution of salaries': This chart will give an overview of how salaries are spread across the dataset,'proportion of employees in different department':
This provides a visual representation of the distribution of employees across various departments, the salary distribution is almost normal, with a peak around the mean salary.
Ichoose grouping by the 'Year' column and calculating summary statistics for the 'TotalPay' column by using groupby and describe() ,average salaries differ across years of experiance .
The numerical coulumn is Years , and after calculate the correlation between salaries and numerical column i conclude it is weak correlation ;This means that i cannot remove any of them .
The scatter plot indicates the relationship between salaries and years of experience,and make it easy to show whether there is a correlation between the two columns.



"""
